query:
    scheduled:
        fixedRate: 10800000
    source:
        columns: case_id, sample_barcode, workflow_schedule_reason, latest_completed_ext_step, latest_completed_step_time, time_current, duration, threshold, delays
        file: /Users/chiuf/tmp/source.sql
    target:
        file: /Users/chiuf/tmp/target.sql
    preTarget:
        file: /Users/chiuf/tmp/pre-target.sql
    postTarget:
        file: /Users/chiuf/tmp/post-target.sql
server:
    port: 8700
source:
    jdbc:
        driverClassName: com.mysql.jdbc.Driver
        hibernate:
            dbcp:
                testWhileIdle: true
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            hbm2ddl:
                auto: update
        password: source123
        url: jdbc:mysql://localhost:33061/source_db?useSSL=false
        username: source_user
process:
    jdbc:
        driverClassName: com.mysql.jdbc.Driver
        hibernate:
            dbcp:
                testWhileIdle: true
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            hbm2ddl:
                auto: update
        password: process123
        url: jdbc:mysql://localhost:33062/process_db?useSSL=false
        username: process_user
target:
    jdbc:
        driverClassName: com.mysql.jdbc.Driver
        hibernate:
            dbcp:
                testWhileIdle: true
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            hbm2ddl:
                auto: update
        password: target123
        url: jdbc:mysql://localhost:33063/target_db?useSSL=false
        username: target_user
spring:
    mail:
        host: localhost
        port: 1025
