query:
    scheduled:
        fixedRate: 10800000
        cron: 0 0 0/3 * * ?
    source:
        columns: CASE_ID, BLOOD, SAMPLE_CREATEDT, MATRIXBARCODE, MATRIXRACK, EXTRACTION, NGS, MLPA, FRAX, CONFIRMATION, ASURAGEN, MANUAL
        file: /Users/felixchiu/tmp/source.sql
    target:
        file: /Users/felixchiu/tmp/target.sql
    preTarget:
        file: /Users/felixchiu/tmp/pre-target.sql
    postTarget:
        file:
server:
    port: 8700
source:
    jdbc:
        driverClassName: oracle.jdbc.driver.OracleDriver
        hibernate:
            dbcp:
                testWhileIdle: true
            dialect: org.hibernate.dialect.Oracle10gDialect
            hbm2ddl:
                auto: validate
        password: 422g5DQZKXgJGd3E
        url: jdbc:oracle:thin:@engplbvrds01.cxtggy06pyij.us-west-2.rds.amazonaws.com:1521/ORCL
        username: ro_ywei
process:
    jdbc:
        driverClassName: com.mysql.jdbc.Driver
        hibernate:
            dbcp:
                testWhileIdle: true
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            hbm2ddl:
                auto: update
        password: Stop912
        url: jdbc:mysql://lims-db-readonly.natera.local:3306/reporting?useSSL=false
        username: easerviceaccount
target:
    jdbc:
        driverClassName: com.mysql.jdbc.Driver
        hibernate:
            dbcp:
                testWhileIdle: true
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            hbm2ddl:
                auto: update
        password: Stop912
        url: jdbc:mysql://lims-db-readonly.natera.local:3306/reporting?useSSL=false
        username: easerviceaccount
spring:
    mail:
        host: 127.0.0.1
        port: 1025
