@startuml

'idea.partialRender

title Just Copy Workflow

"Process Service" -> "Pre-Target Process" : Run pre-target sql
"Pre-Target Process" --> "Process Service" : Success / Failure
"Process Service" -> "Source Data Service" : Run source sql
"Source Data Service" -> "Target Data Service" : Submit data model
group Insert Record
    loop for each row
        "Target Data Service" -> "Database" : Insert Record
end
"Target Data Service" --> "Source Data Service" : Respond number of updates
"Source Data Service" --> "Process Service" : Response completion
"Process Service" -> "Post-Target Service" : Post process
"Post-Target Service" --> "Process Service" : Complete post process
@enduml